name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '15 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch pfizer data
      run: |-
        bash pfizer.sh > pfizer.csv
    - name: Fetch moderna data
      run: |-
        bash moderna.sh > moderna.csv
    - name: Fetch vaccination data
      run: |-
        bash vaccination_data.sh > vaccination_data.json
    - name: Fetch vaccination trends
      run: |-
        bash vaccination_trends.sh > vaccination_trends.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
